### ISSUE TITLE
웹 프론트엔드 구글 크롬 개발자도구에서 cookie 확인할 수 없는 문제

### ISSUE THREAD

**Issue by YesolLee421** [avon-dev/server-test#1]
## 문제
localhost:3000 (웹 프론트엔드)에서 로그인 시도 시 원래 세션 로그인 정보가 'connect.sid'라는 이름으로 쿠키에 저장되어야 함. 근데 localhost:3000 쿠키는 없고 서버에 쿠키가 저장됨.
- **실험**: chrome://settings/siteData 해당 주소에서 모든 쿠키 확인 가능
- **특이점**: 로그인 -> 서버에 쿠키 저장됨 -> 내 정보 확인 시도했을 때 확인됨. 서버 쿠키 삭제하면 확인 안 됨. 즉 서버에 저장된 쿠키를 이용해서 기능 이용이 가능하다.

## 예상되는 원인
프론트엔드 도메인과 resource 요청하는 백엔드 도메인이 달라서 생기는 cross-origin http request 관련 문제인 듯. 현재 백엔드는 aws에 올려져있고 웹 프론트엔드는 localhost를 사용하고 있는데 브라우저 정책 상 같은 도메인(서브 도메인 포함)에서만 cookie를 받는다고 한다.

## 시도해 본 것
- aws서버쪽: cors 패키지 설정, res.header 설정, session.cookie 설정
- front쪽: localhost:3000에서 로그인 시도->db 접근해서 해당 객체는 받아오는데 쿠키 없음

### 서버: res.header 설정
```javascript
// app.js
app.use(function (req, res, next) {
  res.header('Access-Control-Allow-Origin', 'localhost');
  res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE');
  res.header('Access-Control-Allow-Header','*');
  next();
});
```

### 서버: npm cors() 패키지 설정
```javascript
// app.js
if (prod) { // aws서버는 prod 모드임
  app.use(cors({
    origin: true,
    allowedHeaders: 'Origin, X-Requested-With, Content-Type, Accept, authorization',
    credentials: true,
  }));
}
```

### 서버: express-session cookie 설정
```javascript
// app.js
app.use(session({
  resave: false,
  saveUninitialized: false,
  secret: process.env.COOKIE_SECRET,
  cookie: {
      httpOnly: true,
      secure: false,
      domain: prod && "54.180.118.35" // 이 줄 추가. 도메인에 서버ip넣으니 서버에 쿠키 저장됨
  },
}));
```

**Comment by YesolLee421** [comment]
결국 웹 프론트엔드도 언젠간 aws에 올려야 할텐데 올려서 도메인이 같아지면 오히려 쉽게 저장될 것 같기도 합니다.

**Comment by newoo** [comment]
현재 이슈가 정확히 무엇인지 모르겠음...
AWS서버에 쿠키가 저장되는데, 클라이언트가 쿠키 기반으로 통신을 어떻게 하는 것이며...
현재 웹프론트 코드가 서버에 없는 상황에서 쿠키관련 테스트가 진행되고 있었던 건가요??
그렇다면 안 되는 것이 맞다고 봅니다. 
웹 프론트엔드 코드도 AWS서버에 올라간 후에 다시 테스트해보는 것이 좋을 것 같아요

1. 웹 프론트엔드 코드를 AWS서버에 빨리 올린다.
2. 쿠키없이 다른 테스트가 진행되게 한다.

2가지 선택사항 중에 하나 선택해서 진행하는 것이 어떨까 합니다

**Comment by YesolLee421** [comment]
웹 프론트엔드 코드도 AWS에 올려서 해결함.
